# Generated by Django 4.0.6 on 2022-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.CharField(max_length=50)),
                ('return_date', models.CharField(max_length=50)),
                ('departure_station_id', models.IntegerField()),
                ('departure_station_name', models.CharField(max_length=50)),
                ('return_station_id', models.IntegerField()),
                ('return_station_name', models.CharField(max_length=50)),
                ('covered_distance', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
