# Generated by Django 4.0.6 on 2022-07-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey_model', '0002_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='fid',
        ),
    ]
