# Generated by Django 4.0.6 on 2022-07-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey_model', '0003_remove_station_fid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='city',
            new_name='city_finnish',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='coodinate_x',
            new_name='coordinate_x',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='coodinate_y',
            new_name='coordinate_y',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='name_swidish',
            new_name='name_swedish',
        ),
    ]
